const mongoose = require('mongoose');
const Product = require('../models/Product');
const Category = require('../models/Category');
const { products } = require('../data/products');
const { categories: serverCategories } = require('../data/categories');
const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../../.env') });

const seedServerData = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI, {
      dbName: process.env.MONGODB_DB || 'pwa-storefront',
    });
    console.log('MongoDB connected for seeding');

    // Clear existing data (optional - comment out if you want to keep existing data)
    // await Product.deleteMany({});
    // await Category.deleteMany({});

    // Create categories first
    const categoryMap = {};
    for (const catData of serverCategories) {
      let category = await Category.findOne({ name: catData.name });
      if (!category) {
        category = new Category({
          name: catData.name,
          slug: catData.name.toLowerCase().replace(/\s+/g, '-'),
          isActive: true,
        });
        await category.save();
      }
      categoryMap[catData.name] = category._id;
    }

    // Convert and insert products
    const productsToInsert = [];
    for (const productData of products) {
      // Find or create category
      const categoryId = categoryMap[productData.category];
      if (!categoryId) {
        console.warn(`Category "${productData.category}" not found, skipping product: ${productData.name}`);
        continue;
      }

      // Calculate prices
      let salePrice = productData.price;
      let originalPrice = null;
      if (productData.discount > 0) {
        salePrice = productData.price * (1 - productData.discount / 100);
        originalPrice = productData.price;
      }

      // Convert server format to backend format
      const backendProduct = {
        name: productData.name,
        description: productData.description,
        shortDescription: productData.shortDesc,
        price: parseFloat(originalPrice?.toFixed(2) || salePrice.toFixed(2)),
        discountPrice: originalPrice ? parseFloat(salePrice.toFixed(2)) : null,
        images: [{
          url: productData.image,
          alt: productData.name,
          isPrimary: true,
        }],
        category: categoryId,
        stock: productData.stock || 0,
        isActive: true,
        // SKU will be auto-generated by pre-save hook
      };

      // Check if product already exists
      const existingProduct = await Product.findOne({ name: productData.name });
      if (!existingProduct) {
        productsToInsert.push(backendProduct);
      }
    }

    if (productsToInsert.length > 0) {
      await Product.insertMany(productsToInsert);
      console.log(`✅ Successfully imported ${productsToInsert.length} products from server folder format`);
    } else {
      console.log('ℹ️  No new products to import');
    }

    console.log('✅ Seeding completed!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error);
    process.exit(1);
  }
};

// Run seeder
if (require.main === module) {
  seedServerData();
}

module.exports = { seedServerData };

